/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as BookingPricingRouteImport } from './routes/booking-pricing'
import { Route as BookingDatetimeRouteImport } from './routes/booking-datetime'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as BookingCheckoutRouteImport } from './routes/booking-checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffLeaveRouteImport } from './routes/staff.leave'
import { Route as StaffJobsRouteImport } from './routes/staff.jobs'
import { Route as BookingServiceRouteImport } from './routes/booking.$service'
import { Route as BookingDetailsIdRouteImport } from './routes/booking-details.$id'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobAssignmentRouteImport } from './routes/admin.job-assignment'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPricingRoute = BookingPricingRouteImport.update({
  id: '/booking-pricing',
  path: '/booking-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDatetimeRoute = BookingDatetimeRouteImport.update({
  id: '/booking-datetime',
  path: '/booking-datetime',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCheckoutRoute = BookingCheckoutRouteImport.update({
  id: '/booking-checkout',
  path: '/booking-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLeaveRoute = StaffLeaveRouteImport.update({
  id: '/staff/leave',
  path: '/staff/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffJobsRoute = StaffJobsRouteImport.update({
  id: '/staff/jobs',
  path: '/staff/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingServiceRoute = BookingServiceRouteImport.update({
  id: '/booking/$service',
  path: '/booking/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDetailsIdRoute = BookingDetailsIdRouteImport.update({
  id: '/booking-details/$id',
  path: '/booking-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobAssignmentRoute = AdminJobAssignmentRouteImport.update({
  id: '/admin/job-assignment',
  path: '/admin/job-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-checkout': typeof BookingCheckoutRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-datetime': typeof BookingDatetimeRoute
  '/booking-pricing': typeof BookingPricingRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/booking-details/$id': typeof BookingDetailsIdRoute
  '/booking/$service': typeof BookingServiceRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-checkout': typeof BookingCheckoutRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-datetime': typeof BookingDatetimeRoute
  '/booking-pricing': typeof BookingPricingRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/booking-details/$id': typeof BookingDetailsIdRoute
  '/booking/$service': typeof BookingServiceRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-checkout': typeof BookingCheckoutRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/booking-datetime': typeof BookingDatetimeRoute
  '/booking-pricing': typeof BookingPricingRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/tracking': typeof TrackingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/booking-details/$id': typeof BookingDetailsIdRoute
  '/booking/$service': typeof BookingServiceRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking-checkout'
    | '/booking-confirmation'
    | '/booking-datetime'
    | '/booking-pricing'
    | '/customer-dashboard'
    | '/login'
    | '/privacy-policy'
    | '/services'
    | '/tracking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/job-assignment'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/staff'
    | '/booking-details/$id'
    | '/booking/$service'
    | '/staff/jobs'
    | '/staff/leave'
    | '/staff/login'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking-checkout'
    | '/booking-confirmation'
    | '/booking-datetime'
    | '/booking-pricing'
    | '/customer-dashboard'
    | '/login'
    | '/privacy-policy'
    | '/services'
    | '/tracking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/job-assignment'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/staff'
    | '/booking-details/$id'
    | '/booking/$service'
    | '/staff/jobs'
    | '/staff/leave'
    | '/staff/login'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking-checkout'
    | '/booking-confirmation'
    | '/booking-datetime'
    | '/booking-pricing'
    | '/customer-dashboard'
    | '/login'
    | '/privacy-policy'
    | '/services'
    | '/tracking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/job-assignment'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/staff'
    | '/booking-details/$id'
    | '/booking/$service'
    | '/staff/jobs'
    | '/staff/leave'
    | '/staff/login'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingCheckoutRoute: typeof BookingCheckoutRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BookingDatetimeRoute: typeof BookingDatetimeRoute
  BookingPricingRoute: typeof BookingPricingRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TrackingRoute: typeof TrackingRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminJobAssignmentRoute: typeof AdminJobAssignmentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminStaffRoute: typeof AdminStaffRoute
  BookingDetailsIdRoute: typeof BookingDetailsIdRoute
  BookingServiceRoute: typeof BookingServiceRoute
  StaffJobsRoute: typeof StaffJobsRoute
  StaffLeaveRoute: typeof StaffLeaveRoute
  StaffLoginRoute: typeof StaffLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-pricing': {
      id: '/booking-pricing'
      path: '/booking-pricing'
      fullPath: '/booking-pricing'
      preLoaderRoute: typeof BookingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-datetime': {
      id: '/booking-datetime'
      path: '/booking-datetime'
      fullPath: '/booking-datetime'
      preLoaderRoute: typeof BookingDatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-checkout': {
      id: '/booking-checkout'
      path: '/booking-checkout'
      fullPath: '/booking-checkout'
      preLoaderRoute: typeof BookingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/leave': {
      id: '/staff/leave'
      path: '/staff/leave'
      fullPath: '/staff/leave'
      preLoaderRoute: typeof StaffLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/jobs': {
      id: '/staff/jobs'
      path: '/staff/jobs'
      fullPath: '/staff/jobs'
      preLoaderRoute: typeof StaffJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$service': {
      id: '/booking/$service'
      path: '/booking/$service'
      fullPath: '/booking/$service'
      preLoaderRoute: typeof BookingServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-details/$id': {
      id: '/booking-details/$id'
      path: '/booking-details/$id'
      fullPath: '/booking-details/$id'
      preLoaderRoute: typeof BookingDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/job-assignment': {
      id: '/admin/job-assignment'
      path: '/admin/job-assignment'
      fullPath: '/admin/job-assignment'
      preLoaderRoute: typeof AdminJobAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingCheckoutRoute: BookingCheckoutRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  BookingDatetimeRoute: BookingDatetimeRoute,
  BookingPricingRoute: BookingPricingRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TrackingRoute: TrackingRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminJobAssignmentRoute: AdminJobAssignmentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminStaffRoute: AdminStaffRoute,
  BookingDetailsIdRoute: BookingDetailsIdRoute,
  BookingServiceRoute: BookingServiceRoute,
  StaffJobsRoute: StaffJobsRoute,
  StaffLeaveRoute: StaffLeaveRoute,
  StaffLoginRoute: StaffLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
